# ANTIGEN
source /opt/homebrew/share/antigen/antigen.zsh
antigen use oh-my-zsh
antigen bundle brew
antigen bundle git
antigen bundle command-not-found
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle git-extras
antigen bundle osx
antigen theme minimal
antigen apply 

# VARIABLES
export PROMPT="[%n] "
export JAVA_HOME="$(/usr/libexec/java_home -v 17)"
export GPG_TTY=$(tty)

# ALIASES
alias cat="bat"

